version: "3"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: postgres
    shm_size: 1gb
    ports:
      - "5432:5432"
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
  api:
    image: cere-squid
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
      - GQL_PORT=4350
    ports:
      # GraphQL endpoint at port 4350
      - "4350:4350"
    command: ["sqd", "serve:prod"]
    depends_on:
      - db
  processor:
    image: cere-squid
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
      - RPC_CERE_HTTP=wss://archive.mainnet.cere.network/ws
      - SQD_RATE_LIMIT=500
      - SQD_CAPACITY=10
      - SQD_FIRST_BLOCK=8036000
    ports:
      # prometheus metrics exposed at port 3000
      - "3000:3000"
    command: ["sqd", "process:prod"]
    depends_on:
      - db
