version: "3"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data:rw
  processor:
    image: cere-squid
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
      - RPC_CERE_HTTP=wss://archive.testnet.cere.network/ws
      - SQD_RATE_LIMIT=10
      - SQD_CAPACITY=2
      - SQD_FIRST_BLOCK=3725489
    command: ["sqd", "process:prod"]
    depends_on:
      - db
  api:
    image: cere-squid
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
      - GQL_PORT=4350
    ports:
      # GraphQL endpoint at port 4350
      - "4350:4350"
    command: ["sqd", "serve:prod"]
    depends_on:
      - db