version: "3"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
#    volumes:
#      - ./data/db:/var/lib/postgresql/data:rw
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 5s
      timeout: 60s
      retries: 5
  processor:
    image: cere-squid
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
      - RPC_CERE_HTTP=wss://archive.devnet.cere.network/ws
      - SQD_RATE_LIMIT=5000
      - SQD_CAPACITY=100
      - SQD_FIRST_BLOCK=14909
      - TYPES_BUNDLE=/squid/cere-types-bundle.json
    command: ["sqd", "process:prod"]
    depends_on:
      - db
  api:
    image: cere-squid
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
      - GQL_PORT=4350
    ports:
      # GraphQL endpoint at port 4350
      - "4350:4350"
    command: ["sqd", "serve:prod"]
    depends_on:
      - db