export * as system from './system/storage'
export * as balances from './balances/storage'
export * as ddcStaking from './ddc-staking/storage'
export * as ddcNodes from './ddc-nodes/storage'
export * as ddcClusters from './ddc-clusters/storage'
export * as ddcCustomers from './ddc-customers/storage'
export * as ddcPayouts from './ddc-payouts/storage'
