name: Release to dev
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: false
        description: 'Environment to deploy to'
        options:
          - squid
          - squid-2

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/deploy-to-ecr.yaml@master
    with:
      environment: dev
      aws_account_id: ${{ vars.DEV_NETWORK_AWS_ACCOUNT_ID }}
      repository: cere-${{ inputs.environment }}
      file: ./Dockerfile
    secrets: inherit
